// Code generated by mockery v2.46.0. DO NOT EDIT.

package activerecord

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockConfig is an autogenerated mock type for the ConfigInterface type
type MockConfig struct {
	mock.Mock
}

type MockConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfig) EXPECT() *MockConfig_Expecter {
	return &MockConfig_Expecter{mock: &_m.Mock}
}

// GetBool provides a mock function with given fields: confPath, dfl
func (_m *MockConfig) GetBool(confPath string, dfl ...bool) (bool, error) {
	_va := make([]interface{}, len(dfl))
	for _i := range dfl {
		_va[_i] = dfl[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, confPath)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetBool")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...bool) (bool, error)); ok {
		return rf(confPath, dfl...)
	}
	if rf, ok := ret.Get(0).(func(string, ...bool) bool); ok {
		r0 = rf(confPath, dfl...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, ...bool) error); ok {
		r1 = rf(confPath, dfl...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfig_GetBool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBool'
type MockConfig_GetBool_Call struct {
	*mock.Call
}

// GetBool is a helper method to define mock.On call
//   - confPath string
//   - dfl ...bool
func (_e *MockConfig_Expecter) GetBool(confPath interface{}, dfl ...interface{}) *MockConfig_GetBool_Call {
	return &MockConfig_GetBool_Call{Call: _e.mock.On("GetBool",
		append([]interface{}{confPath}, dfl...)...)}
}

func (_c *MockConfig_GetBool_Call) Run(run func(confPath string, dfl ...bool)) *MockConfig_GetBool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]bool, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(bool)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockConfig_GetBool_Call) Return(_a0 bool, _a1 error) *MockConfig_GetBool_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfig_GetBool_Call) RunAndReturn(run func(string, ...bool) (bool, error)) *MockConfig_GetBool_Call {
	_c.Call.Return(run)
	return _c
}

// GetBoolIfExists provides a mock function with given fields: confPath
func (_m *MockConfig) GetBoolIfExists(confPath string) (bool, bool, error) {
	ret := _m.Called(confPath)

	if len(ret) == 0 {
		panic("no return value specified for GetBoolIfExists")
	}

	var r0 bool
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (bool, bool, error)); ok {
		return rf(confPath)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(confPath)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(confPath)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(confPath)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockConfig_GetBoolIfExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBoolIfExists'
type MockConfig_GetBoolIfExists_Call struct {
	*mock.Call
}

// GetBoolIfExists is a helper method to define mock.On call
//   - confPath string
func (_e *MockConfig_Expecter) GetBoolIfExists(confPath interface{}) *MockConfig_GetBoolIfExists_Call {
	return &MockConfig_GetBoolIfExists_Call{Call: _e.mock.On("GetBoolIfExists", confPath)}
}

func (_c *MockConfig_GetBoolIfExists_Call) Run(run func(confPath string)) *MockConfig_GetBoolIfExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfig_GetBoolIfExists_Call) Return(value bool, ok bool, err error) *MockConfig_GetBoolIfExists_Call {
	_c.Call.Return(value, ok, err)
	return _c
}

func (_c *MockConfig_GetBoolIfExists_Call) RunAndReturn(run func(string) (bool, bool, error)) *MockConfig_GetBoolIfExists_Call {
	_c.Call.Return(run)
	return _c
}

// GetDuration provides a mock function with given fields: confPath, dfl
func (_m *MockConfig) GetDuration(confPath string, dfl ...time.Duration) (time.Duration, error) {
	_va := make([]interface{}, len(dfl))
	for _i := range dfl {
		_va[_i] = dfl[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, confPath)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetDuration")
	}

	var r0 time.Duration
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...time.Duration) (time.Duration, error)); ok {
		return rf(confPath, dfl...)
	}
	if rf, ok := ret.Get(0).(func(string, ...time.Duration) time.Duration); ok {
		r0 = rf(confPath, dfl...)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	if rf, ok := ret.Get(1).(func(string, ...time.Duration) error); ok {
		r1 = rf(confPath, dfl...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfig_GetDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDuration'
type MockConfig_GetDuration_Call struct {
	*mock.Call
}

// GetDuration is a helper method to define mock.On call
//   - confPath string
//   - dfl ...time.Duration
func (_e *MockConfig_Expecter) GetDuration(confPath interface{}, dfl ...interface{}) *MockConfig_GetDuration_Call {
	return &MockConfig_GetDuration_Call{Call: _e.mock.On("GetDuration",
		append([]interface{}{confPath}, dfl...)...)}
}

func (_c *MockConfig_GetDuration_Call) Run(run func(confPath string, dfl ...time.Duration)) *MockConfig_GetDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]time.Duration, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(time.Duration)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockConfig_GetDuration_Call) Return(_a0 time.Duration, _a1 error) *MockConfig_GetDuration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfig_GetDuration_Call) RunAndReturn(run func(string, ...time.Duration) (time.Duration, error)) *MockConfig_GetDuration_Call {
	_c.Call.Return(run)
	return _c
}

// GetDurationIfExists provides a mock function with given fields: confPath
func (_m *MockConfig) GetDurationIfExists(confPath string) (time.Duration, bool, error) {
	ret := _m.Called(confPath)

	if len(ret) == 0 {
		panic("no return value specified for GetDurationIfExists")
	}

	var r0 time.Duration
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (time.Duration, bool, error)); ok {
		return rf(confPath)
	}
	if rf, ok := ret.Get(0).(func(string) time.Duration); ok {
		r0 = rf(confPath)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(confPath)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(confPath)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockConfig_GetDurationIfExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDurationIfExists'
type MockConfig_GetDurationIfExists_Call struct {
	*mock.Call
}

// GetDurationIfExists is a helper method to define mock.On call
//   - confPath string
func (_e *MockConfig_Expecter) GetDurationIfExists(confPath interface{}) *MockConfig_GetDurationIfExists_Call {
	return &MockConfig_GetDurationIfExists_Call{Call: _e.mock.On("GetDurationIfExists", confPath)}
}

func (_c *MockConfig_GetDurationIfExists_Call) Run(run func(confPath string)) *MockConfig_GetDurationIfExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfig_GetDurationIfExists_Call) Return(_a0 time.Duration, _a1 bool, _a2 error) *MockConfig_GetDurationIfExists_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockConfig_GetDurationIfExists_Call) RunAndReturn(run func(string) (time.Duration, bool, error)) *MockConfig_GetDurationIfExists_Call {
	_c.Call.Return(run)
	return _c
}

// GetInt provides a mock function with given fields: confPath, dfl
func (_m *MockConfig) GetInt(confPath string, dfl ...int64) (int64, error) {
	_va := make([]interface{}, len(dfl))
	for _i := range dfl {
		_va[_i] = dfl[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, confPath)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetInt")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...int64) (int64, error)); ok {
		return rf(confPath, dfl...)
	}
	if rf, ok := ret.Get(0).(func(string, ...int64) int64); ok {
		r0 = rf(confPath, dfl...)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string, ...int64) error); ok {
		r1 = rf(confPath, dfl...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfig_GetInt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInt'
type MockConfig_GetInt_Call struct {
	*mock.Call
}

// GetInt is a helper method to define mock.On call
//   - confPath string
//   - dfl ...int64
func (_e *MockConfig_Expecter) GetInt(confPath interface{}, dfl ...interface{}) *MockConfig_GetInt_Call {
	return &MockConfig_GetInt_Call{Call: _e.mock.On("GetInt",
		append([]interface{}{confPath}, dfl...)...)}
}

func (_c *MockConfig_GetInt_Call) Run(run func(confPath string, dfl ...int64)) *MockConfig_GetInt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]int64, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(int64)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockConfig_GetInt_Call) Return(_a0 int64, _a1 error) *MockConfig_GetInt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfig_GetInt_Call) RunAndReturn(run func(string, ...int64) (int64, error)) *MockConfig_GetInt_Call {
	_c.Call.Return(run)
	return _c
}

// GetIntIfExists provides a mock function with given fields: confPath
func (_m *MockConfig) GetIntIfExists(confPath string) (int64, bool, error) {
	ret := _m.Called(confPath)

	if len(ret) == 0 {
		panic("no return value specified for GetIntIfExists")
	}

	var r0 int64
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (int64, bool, error)); ok {
		return rf(confPath)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(confPath)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(confPath)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(confPath)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockConfig_GetIntIfExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIntIfExists'
type MockConfig_GetIntIfExists_Call struct {
	*mock.Call
}

// GetIntIfExists is a helper method to define mock.On call
//   - confPath string
func (_e *MockConfig_Expecter) GetIntIfExists(confPath interface{}) *MockConfig_GetIntIfExists_Call {
	return &MockConfig_GetIntIfExists_Call{Call: _e.mock.On("GetIntIfExists", confPath)}
}

func (_c *MockConfig_GetIntIfExists_Call) Run(run func(confPath string)) *MockConfig_GetIntIfExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfig_GetIntIfExists_Call) Return(_a0 int64, _a1 bool, _a2 error) *MockConfig_GetIntIfExists_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockConfig_GetIntIfExists_Call) RunAndReturn(run func(string) (int64, bool, error)) *MockConfig_GetIntIfExists_Call {
	_c.Call.Return(run)
	return _c
}

// GetString provides a mock function with given fields: confPath, dfl
func (_m *MockConfig) GetString(confPath string, dfl ...string) (string, error) {
	_va := make([]interface{}, len(dfl))
	for _i := range dfl {
		_va[_i] = dfl[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, confPath)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetString")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...string) (string, error)); ok {
		return rf(confPath, dfl...)
	}
	if rf, ok := ret.Get(0).(func(string, ...string) string); ok {
		r0 = rf(confPath, dfl...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, ...string) error); ok {
		r1 = rf(confPath, dfl...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfig_GetString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetString'
type MockConfig_GetString_Call struct {
	*mock.Call
}

// GetString is a helper method to define mock.On call
//   - confPath string
//   - dfl ...string
func (_e *MockConfig_Expecter) GetString(confPath interface{}, dfl ...interface{}) *MockConfig_GetString_Call {
	return &MockConfig_GetString_Call{Call: _e.mock.On("GetString",
		append([]interface{}{confPath}, dfl...)...)}
}

func (_c *MockConfig_GetString_Call) Run(run func(confPath string, dfl ...string)) *MockConfig_GetString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockConfig_GetString_Call) Return(_a0 string, _a1 error) *MockConfig_GetString_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfig_GetString_Call) RunAndReturn(run func(string, ...string) (string, error)) *MockConfig_GetString_Call {
	_c.Call.Return(run)
	return _c
}

// GetStringIfExists provides a mock function with given fields: confPath
func (_m *MockConfig) GetStringIfExists(confPath string) (string, bool, error) {
	ret := _m.Called(confPath)

	if len(ret) == 0 {
		panic("no return value specified for GetStringIfExists")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (string, bool, error)); ok {
		return rf(confPath)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(confPath)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(confPath)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(confPath)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockConfig_GetStringIfExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStringIfExists'
type MockConfig_GetStringIfExists_Call struct {
	*mock.Call
}

// GetStringIfExists is a helper method to define mock.On call
//   - confPath string
func (_e *MockConfig_Expecter) GetStringIfExists(confPath interface{}) *MockConfig_GetStringIfExists_Call {
	return &MockConfig_GetStringIfExists_Call{Call: _e.mock.On("GetStringIfExists", confPath)}
}

func (_c *MockConfig_GetStringIfExists_Call) Run(run func(confPath string)) *MockConfig_GetStringIfExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfig_GetStringIfExists_Call) Return(_a0 string, _a1 bool, _a2 error) *MockConfig_GetStringIfExists_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockConfig_GetStringIfExists_Call) RunAndReturn(run func(string) (string, bool, error)) *MockConfig_GetStringIfExists_Call {
	_c.Call.Return(run)
	return _c
}

// GetStrings provides a mock function with given fields: confPath, dfl
func (_m *MockConfig) GetStrings(confPath string, dfl []string) ([]string, error) {
	ret := _m.Called(confPath, dfl)

	if len(ret) == 0 {
		panic("no return value specified for GetStrings")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []string) ([]string, error)); ok {
		return rf(confPath, dfl)
	}
	if rf, ok := ret.Get(0).(func(string, []string) []string); ok {
		r0 = rf(confPath, dfl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = rf(confPath, dfl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfig_GetStrings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStrings'
type MockConfig_GetStrings_Call struct {
	*mock.Call
}

// GetStrings is a helper method to define mock.On call
//   - confPath string
//   - dfl []string
func (_e *MockConfig_Expecter) GetStrings(confPath interface{}, dfl interface{}) *MockConfig_GetStrings_Call {
	return &MockConfig_GetStrings_Call{Call: _e.mock.On("GetStrings", confPath, dfl)}
}

func (_c *MockConfig_GetStrings_Call) Run(run func(confPath string, dfl []string)) *MockConfig_GetStrings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]string))
	})
	return _c
}

func (_c *MockConfig_GetStrings_Call) Return(_a0 []string, _a1 error) *MockConfig_GetStrings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfig_GetStrings_Call) RunAndReturn(run func(string, []string) ([]string, error)) *MockConfig_GetStrings_Call {
	_c.Call.Return(run)
	return _c
}

// GetStruct provides a mock function with given fields: confPath, valuePtr
func (_m *MockConfig) GetStruct(confPath string, valuePtr interface{}) (bool, error) {
	ret := _m.Called(confPath, valuePtr)

	if len(ret) == 0 {
		panic("no return value specified for GetStruct")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, interface{}) (bool, error)); ok {
		return rf(confPath, valuePtr)
	}
	if rf, ok := ret.Get(0).(func(string, interface{}) bool); ok {
		r0 = rf(confPath, valuePtr)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, interface{}) error); ok {
		r1 = rf(confPath, valuePtr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfig_GetStruct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStruct'
type MockConfig_GetStruct_Call struct {
	*mock.Call
}

// GetStruct is a helper method to define mock.On call
//   - confPath string
//   - valuePtr interface{}
func (_e *MockConfig_Expecter) GetStruct(confPath interface{}, valuePtr interface{}) *MockConfig_GetStruct_Call {
	return &MockConfig_GetStruct_Call{Call: _e.mock.On("GetStruct", confPath, valuePtr)}
}

func (_c *MockConfig_GetStruct_Call) Run(run func(confPath string, valuePtr interface{})) *MockConfig_GetStruct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interface{}))
	})
	return _c
}

func (_c *MockConfig_GetStruct_Call) Return(_a0 bool, _a1 error) *MockConfig_GetStruct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfig_GetStruct_Call) RunAndReturn(run func(string, interface{}) (bool, error)) *MockConfig_GetStruct_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfig creates a new instance of MockConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfig {
	mock := &MockConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
